name: First workflow

run-name: Deploy to ${{ inputs.deploy__target }} by @${{ github.actor }}

on: 
  push:
   branches:
     - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Hello world!
        run: echo "Hello from ${{ github.worflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

